[build]
  publish = "build"
  command = "yarn build"
  functions = "functions"

[dev]
  framework = "#custom"
  command = "yarn parcel"
  publish = "public"
  targetPort = 3001
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
